export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILTURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const LOAD_JOBS_SUCCESS = "LOAD_JOBS_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_APPLICANTS_SUCCESS = "LOAD_APPLICANTS_SUCCESS";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_APPLICANTS_SUCCESS = "CREATE_APPLICANTS_SUCCESS";

export const UPDATE_JOBS_SUCCESS = "UPDATE_JOBS_SUCCESS";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_APPLICANTS_SUCCESS = "UPDATE_APPLICANTS_SUCCESS";

export const SET_STATUS_FILTER = "SET_STATUS_FILTER";
export const SET_ROLE_FILTER = "SET_ROLE_FILTER";

export const StatusFilters = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_CLOSED: "SHOW_CLOSED",
  SHOW_DRAFT: "SHOW_DRAFT",
  SHOW_PUBLISHED: "SHOW_PUBLISHED"
};

export const RoleFilters = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_OWNER: "SHOW_OWNER",
  SHOw_VIEWER: "SHOW_VIEWER",
  SHOW_INTERVIEWER: "SHOW_INTERVIEWER"
};
