export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const LOAD_JOBS_SUCCESS = 'LOAD_JOBS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_APPLICANTS_SUCCESS = 'LOAD_APPLICANTS_SUCCESS';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';

export const UPDATE_JOBS_SUCCESS = 'UPDATE_JOBS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_APPLICANTS_SUCCESS = 'UPDATE_APPLICANTS_SUCCESS';